version: '3.7'

services:
  kafka-broker:
    container_name: kafka-broker
    build:
      context: kafka-zookeeper/
      dockerfile: Dockerfile
      target: kafka
    image: kafka-zookeeper:latest
    ports:
      - 9092:9092

  kafdrop-ui:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop-ui
    env_file:
      - kafka-zookeeper/.env
    ports:
      - 9091:9000
    depends_on:
      - kafka-broker
